# Generated by Django 5.0.6 on 2024-06-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educationapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='quantity',
        ),
    ]
